# Generated by Django 3.1 on 2021-12-17 15:13

from django.db import migrations, models
import django.db.models.deletion
import storebot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_user_id', models.CharField(max_length=255, verbose_name='Mijozning telegram IDsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_ordered', models.BooleanField(default=False, null=True, verbose_name='Buyurtma qilingan')),
                ('is_finished', models.BooleanField(default=False, null=True, verbose_name='Hal etilganligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritildi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirildi")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, verbose_name="To'liq ismi")),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Telefon raqami')),
                ('user_id', models.IntegerField(default=0, verbose_name='Telegram foydalanuvchi IDsi')),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='callback_data')),
                ('description', models.TextField(blank=True, verbose_name='Mahsulot haqida')),
                ('price', models.FloatField(default=0.0, verbose_name='Narxi')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Mavjudligi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storebot.category', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=storebot.models.get_file_path, verbose_name='Mahsulat rasmi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storebot.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_ordered', models.BooleanField(default=False, null=True, verbose_name='Buyurtma qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritildi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirildi")),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storebot.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storebot.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma jihoz',
                'verbose_name_plural': 'Buyurtma jihozlar',
            },
        ),
    ]
