# Generated by Django 3.1 on 2021-12-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0003_auto_20211219_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID'),
        ),
    ]
