# Generated by Django 3.1 on 2021-12-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0005_auto_20211219_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Telegram foydalanuvchi IDsi'),
        ),
    ]
