# Generated by Django 3.1 on 2021-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0006_client_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client_user_id',
            field=models.IntegerField(max_length=255, verbose_name='Mijozning telegram IDsi'),
        ),
    ]
