# Generated by Django 3.1 on 2021-12-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0008_auto_20211220_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client_user_id',
            field=models.IntegerField(unique=True, verbose_name='Mijozning telegram IDsi'),
        ),
    ]
