# Generated by Django 3.1 on 2021-12-21 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0009_auto_20211220_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storebot.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storebot.product', verbose_name='Mahsulot')),
            ],
        ),
    ]
