# Generated by Django 3.1 on 2021-12-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0010_ordereditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
