# Generated by Django 3.1 on 2021-12-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0011_auto_20211221_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordereditems',
            options={'verbose_name': 'Buyurtma qilngan mahsulot', 'verbose_name_plural': 'Buyurtma qilngan mahsulotlar'},
        ),
    ]
