# Generated by Django 3.1 on 2021-12-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0013_cartitem_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_ordered',
        ),
    ]
