# Generated by Django 3.1 on 2021-12-21 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0015_auto_20211221_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_code',
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True, verbose_name='buyurtma kodi'),
        ),
    ]
