# Generated by Django 3.1 on 2021-12-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0017_auto_20211221_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='buyAllItems',
            field=models.BooleanField(default=False, verbose_name='Barcha narsani sotib oladimi?'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_code',
            field=models.CharField(max_length=36, verbose_name='buyurtma kodi'),
        ),
    ]
