# Generated by Django 3.1 on 2021-12-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0022_activecartitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveCartItems',
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.CharField(max_length=255, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.CharField(max_length=255, null=True, verbose_name='Longitude'),
        ),
    ]
