# Generated by Django 3.1 on 2021-12-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0024_client_shoppedbefore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='shoppedBefore',
            new_name='shopped_before',
        ),
    ]
