# Generated by Django 3.1 on 2021-12-28 16:15

from django.db import migrations, models
import django.db.models.deletion
import storebot.models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0025_auto_20211225_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=255, verbose_name='Longitude')),
                ('latitude', models.CharField(max_length=255, verbose_name='Latitude')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='client',
            name='longitude',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to=storebot.models.get_file_path, verbose_name='Mahsulat rasmi'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='clientlocations',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storebot.client'),
        ),
    ]
