# Generated by Django 3.1 on 2021-12-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0026_auto_20211228_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlocations',
            old_name='client_id',
            new_name='client',
        ),
    ]
