# Generated by Django 3.1 on 2021-12-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0027_auto_20211228_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlocations',
            name='client',
            field=models.CharField(max_length=255, verbose_name='User_id'),
        ),
    ]
