# Generated by Django 3.1 on 2021-12-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0028_auto_20211228_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlocations',
            old_name='client',
            new_name='client_id',
        ),
    ]
