# Generated by Django 3.1 on 2021-12-30 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0029_auto_20211228_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlocations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kiritildi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientlocations',
            name='client_id',
            field=models.IntegerField(verbose_name='User_id'),
        ),
    ]
