# Generated by Django 3.1 on 2022-01-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storebot', '0031_auto_20220108_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='user_id',
            field=models.IntegerField(verbose_name='Client telegram Id si'),
        ),
    ]
